apiVersion: v1
kind: ConfigMap
metadata:
  name: ollive-app-config
  namespace: ollive-assignment
data:
  DATABASE_HOST: ollive-postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: ollive_inference
  DATABASE_USER: postgres
  DEFAULT_PROVIDER: auto
  LLM_MODEL: gpt-4.1-mini
  ANTHROPIC_MODEL: claude-3-5-sonnet-latest
