apiVersion: v1
kind: Secret
metadata:
  name: ollive-app-secrets
  namespace: ollive-assignment
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@ollive-postgres:5432/ollive_inference
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  POSTGRES_PASSWORD: postgres
